---

- name: Get Port and Vlan data for the node
  command: "./scripts/get_portsAndVlans.py {{ global_vlans }}"
  run_once: true
  register: ports_and_vlans_list

- name: Modify string to
  set_fact:
    ports_list: "{{ ports_and_vlans_list.stdout | from_json }}"
