---

- name: facts testing
  hosts: core_switches
  connection: local
  gather_facts: no


  tasks:


  - name: run my script!
    command: ./scripts/get_portsAndVlans.py
    run_once: true
    register: ports_and_vlans_list

  - name: Modify string to
    set_fact:
      ports_list: "{{ ports_and_vlans_list.stdout | from_json }}"

  - name: CURRENT VLAN LIST
    debug:
      var: ports_list
      verbosity: 3

  - name: indexed loop demo
    debug:
      msg: "at array position {{ item.port }}"
      verbosity: 3
    with_items: "{{ ports_list }}"

  - name: Ensure port is configured to be access port
    nxos_interface:
      provider: "{{ nxos_provider }}"
      interface: "{{ item.port }}"
      description: "a port"
      mode: layer2
    with_items: "{{ ports_list }}"

  - name: Ensure interfaces is configured for correct vlans
    nxos_switchport:
      provider: "{{ nxos_provider }}"
      interface: "{{ item.port }}"
      trunk_allowed_vlans: "{{ item.portvlans }}"
      mode: trunk
      transport: cli
    with_items: "{{ ports_list }}"